# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def set_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 693)
        MainWindow.setFixedSize(1104, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_left_top = QtWidgets.QWidget(self.centralwidget)
        self.widget_left_top.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.widget_left_top.setObjectName("widget_left_top")
        self.label_welcome = QtWidgets.QLabel(self.widget_left_top)
        self.label_welcome.setGeometry(QtCore.QRect(40, 40, 121, 41))
        self.label_welcome.setObjectName("label_welcome")
        self.widget_left_bottom = QtWidgets.QWidget(self.centralwidget)
        self.widget_left_bottom.setGeometry(QtCore.QRect(0, 130, 211, 531))
        self.widget_left_bottom.setObjectName("widget_left_bottom")
        self.groupBox_func = QtWidgets.QGroupBox(self.widget_left_bottom)
        self.groupBox_func.setGeometry(QtCore.QRect(20, 30, 151, 171))
        self.groupBox_func.setObjectName("groupBox_func")
        self.btn_face_dect = QtWidgets.QPushButton(self.groupBox_func)
        self.btn_face_dect.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.btn_face_dect.setObjectName("btn_face_dect")
        self.btn_face_reco = QtWidgets.QPushButton(self.groupBox_func)
        self.btn_face_reco.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.btn_face_reco.setObjectName("btn_face_reco")
        self.btn_face_anal = QtWidgets.QPushButton(self.groupBox_func)
        self.btn_face_anal.setGeometry(QtCore.QRect(0, 110, 151, 41))
        self.btn_face_anal.setObjectName("btn_face_anal")
        self.groupBox_data = QtWidgets.QGroupBox(self.widget_left_bottom)
        self.groupBox_data.setGeometry(QtCore.QRect(20, 230, 151, 131))
        self.groupBox_data.setObjectName("groupBox_data")
        self.btn_data_list = QtWidgets.QPushButton(self.groupBox_data)
        self.btn_data_list.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.btn_data_list.setObjectName("btn_data_list")
        self.btn_data_anal = QtWidgets.QPushButton(self.groupBox_data)
        self.btn_data_anal.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.btn_data_anal.setObjectName("btn_data_anal")
        self.groupBox_set = QtWidgets.QGroupBox(self.widget_left_bottom)
        self.groupBox_set.setGeometry(QtCore.QRect(20, 370, 151, 131))
        self.groupBox_set.setObjectName("groupBox_set")
        self.btn_start_set = QtWidgets.QPushButton(self.groupBox_set)
        self.btn_start_set.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.btn_start_set.setObjectName("btn_start_set")
        self.btn_data_set = QtWidgets.QPushButton(self.groupBox_set)
        self.btn_data_set.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.btn_data_set.setObjectName("btn_data_set")
        self.widget_right_bar = QtWidgets.QWidget(self.centralwidget)
        self.widget_right_bar.setGeometry(QtCore.QRect(210, 0, 891, 661))
        self.widget_right_bar.setObjectName("widget_right_bar")
        self.widget_people_show = QtWidgets.QWidget(self.widget_right_bar)
        self.widget_people_show.setGeometry(QtCore.QRect(610, 0, 281, 661))
        self.widget_people_show.setObjectName("widget_people_show")
        self.widget_person_1 = QtWidgets.QWidget(self.widget_people_show)
        self.widget_person_1.setGeometry(QtCore.QRect(30, 110, 221, 131))
        self.widget_person_1.setObjectName("widget_person_1")
        self.label_img_show_1 = QtWidgets.QLabel(self.widget_person_1)
        self.label_img_show_1.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_img_show_1.setObjectName("label_img_show_1")
        self.label_img_info_1 = QtWidgets.QLabel(self.widget_person_1)
        self.label_img_info_1.setGeometry(QtCore.QRect(40, 90, 121, 31))
        self.label_img_info_1.setObjectName("label_img_info_1")
        self.widget_person_2 = QtWidgets.QWidget(self.widget_people_show)
        self.widget_person_2.setGeometry(QtCore.QRect(30, 240, 221, 131))
        self.widget_person_2.setObjectName("widget_person_2")
        self.label_img_show_2 = QtWidgets.QLabel(self.widget_person_2)
        self.label_img_show_2.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_img_show_2.setObjectName("label_img_show_2")
        self.label_img_info_2 = QtWidgets.QLabel(self.widget_person_2)
        self.label_img_info_2.setGeometry(QtCore.QRect(40, 90, 121, 31))
        self.label_img_info_2.setObjectName("label_img_info_2")
        self.widget_person_3 = QtWidgets.QWidget(self.widget_people_show)
        self.widget_person_3.setGeometry(QtCore.QRect(30, 370, 221, 131))
        self.widget_person_3.setObjectName("widget_person_3")
        self.label_img_show_3 = QtWidgets.QLabel(self.widget_person_3)
        self.label_img_show_3.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_img_show_3.setObjectName("label_img_show_3")
        self.label_img_info_3 = QtWidgets.QLabel(self.widget_person_3)
        self.label_img_info_3.setGeometry(QtCore.QRect(40, 90, 121, 31))
        self.label_img_info_3.setObjectName("label_img_info_3")
        self.widget_person_4 = QtWidgets.QWidget(self.widget_people_show)
        self.widget_person_4.setGeometry(QtCore.QRect(30, 500, 221, 131))
        self.widget_person_4.setObjectName("widget_person_4")
        self.label_img_show_4 = QtWidgets.QLabel(self.widget_person_4)
        self.label_img_show_4.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_img_show_4.setObjectName("label_img_show_4")
        self.label_img_info_4 = QtWidgets.QLabel(self.widget_person_4)
        self.label_img_info_4.setGeometry(QtCore.QRect(40, 90, 121, 31))
        self.label_img_info_4.setObjectName("label_img_info_4")
        self.label_info_show = QtWidgets.QLabel(self.widget_people_show)
        self.label_info_show.setGeometry(QtCore.QRect(40, 30, 81, 41))
        self.label_info_show.setObjectName("label_info_show")
        self.label_video = QtWidgets.QLabel(self.widget_right_bar)
        self.label_video.setGeometry(QtCore.QRect(0, 30, 601, 401))
        self.label_video.setObjectName("label_video")
        self.btn_select_algo = QtWidgets.QPushButton(self.widget_right_bar)
        self.btn_select_algo.setGeometry(QtCore.QRect(180, 480, 151, 41))
        self.btn_select_algo.setObjectName("btn_select_algo")
        self.btn_select_class = QtWidgets.QPushButton(self.widget_right_bar)
        self.btn_select_class.setGeometry(QtCore.QRect(180, 540, 151, 41))
        self.btn_select_class.setObjectName("btn_select_class")
        self.btn_open_video = QtWidgets.QPushButton(self.widget_right_bar)
        self.btn_open_video.setGeometry(QtCore.QRect(10, 500, 151, 41))
        self.btn_open_video.setObjectName("btn_open_video")
        self.btn_open_camera = QtWidgets.QPushButton(self.widget_right_bar)
        self.btn_open_camera.setGeometry(QtCore.QRect(10, 450, 151, 41))
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.widget_algo_data = QtWidgets.QWidget(self.widget_right_bar)
        self.widget_algo_data.setGeometry(QtCore.QRect(340, 430, 251, 181))
        self.widget_algo_data.setObjectName("widget_algo_data")
        self.label_algo_data = QtWidgets.QLabel(self.widget_algo_data)
        self.label_algo_data.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label_algo_data.setObjectName("label_algo_data")
        self.label_model_pos = QtWidgets.QLabel(self.widget_algo_data)
        self.label_model_pos.setGeometry(QtCore.QRect(30, 70, 100, 15))
        self.label_model_pos.setObjectName("label_model_pos")
        self.label_accuracy_pos = QtWidgets.QLabel(self.widget_algo_data)
        self.label_accuracy_pos.setGeometry(QtCore.QRect(30, 110, 100, 15))
        self.label_accuracy_pos.setObjectName("label_accuracy_pos")
        self.label_class_pos = QtWidgets.QLabel(self.widget_algo_data)
        self.label_class_pos.setGeometry(QtCore.QRect(30, 150, 100, 15))
        self.label_class_pos.setObjectName("label_class_pos")
        self.btn_save_img = QtWidgets.QPushButton(self.widget_right_bar)
        self.btn_save_img.setGeometry(QtCore.QRect(10, 550, 151, 41))
        self.btn_save_img.setObjectName("btn_save_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_welcome.setText(_translate("MainWindow", "人脸识别系统"))
        self.groupBox_func.setTitle(_translate("MainWindow", "功能"))
        self.btn_face_dect.setText(_translate("MainWindow", "人脸检测"))
        self.btn_face_reco.setText(_translate("MainWindow", "人脸识别"))
        self.btn_face_anal.setText(_translate("MainWindow", "人脸分析"))
        self.groupBox_data.setTitle(_translate("MainWindow", "数据"))
        self.btn_data_list.setText(_translate("MainWindow", "数据列表"))
        self.btn_data_anal.setText(_translate("MainWindow", "数据统计"))
        self.groupBox_set.setTitle(_translate("MainWindow", "设置"))
        self.btn_start_set.setText(_translate("MainWindow", "启动设置"))
        self.btn_data_set.setText(_translate("MainWindow", "数据设置"))
        self.label_img_show_1.setText(_translate("MainWindow", "Person_img_1"))
        self.label_img_info_1.setText(_translate("MainWindow", "Person_info_1"))
        self.label_img_show_2.setText(_translate("MainWindow", "Person_img_2"))
        self.label_img_info_2.setText(_translate("MainWindow", "Person_info_2"))
        self.label_img_show_3.setText(_translate("MainWindow", "Person_img_3"))
        self.label_img_info_3.setText(_translate("MainWindow", "Person_info_3"))
        self.label_img_show_4.setText(_translate("MainWindow", "Person_img_4"))
        self.label_img_info_4.setText(_translate("MainWindow", "Person_info_4"))
        self.label_info_show.setText(_translate("MainWindow", "信息展示"))
        self.label_video.setText(_translate("MainWindow", "Video "))
        self.btn_select_algo.setText(_translate("MainWindow", "选择算法"))
        self.btn_select_class.setText(_translate("MainWindow", "选择分类器"))
        self.btn_open_video.setText(_translate("MainWindow", "打开视频"))
        self.btn_open_camera.setText(_translate("MainWindow", "打开摄像头"))
        self.label_algo_data.setText(_translate("MainWindow", "算法数据"))
        self.label_model_pos.setText(_translate("MainWindow", "模型"))
        self.label_accuracy_pos.setText(_translate("MainWindow", "准确率"))
        self.label_class_pos.setText(_translate("MainWindow", "分类器"))
        self.btn_save_img.setText(_translate("MainWindow", "抓取照片"))


