# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 211, 131))
        self.widget.setObjectName("widget")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 121, 41))
        self.label_7.setObjectName("label_7")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 130, 211, 531))
        self.widget_2.setObjectName("widget_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 151, 171))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 110, 151, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 230, 151, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 370, 151, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 30, 151, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 70, 151, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(210, 0, 891, 661))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setGeometry(QtCore.QRect(610, 0, 281, 661))
        self.widget_4.setObjectName("widget_4")
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setGeometry(QtCore.QRect(20, 110, 221, 131))
        self.widget_6.setObjectName("widget_6")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 121, 31))
        self.label_5.setObjectName("label_5")
        self.widget_9 = QtWidgets.QWidget(self.widget_4)
        self.widget_9.setGeometry(QtCore.QRect(20, 240, 221, 121))
        self.widget_9.setObjectName("widget_9")
        self.label_10 = QtWidgets.QLabel(self.widget_9)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 191, 61))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_9)
        self.label_11.setGeometry(QtCore.QRect(40, 80, 121, 31))
        self.label_11.setObjectName("label_11")
        self.widget_8 = QtWidgets.QWidget(self.widget_4)
        self.widget_8.setGeometry(QtCore.QRect(20, 360, 221, 131))
        self.widget_8.setObjectName("widget_8")
        self.label_8 = QtWidgets.QLabel(self.widget_8)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 191, 61))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget_8)
        self.label_9.setGeometry(QtCore.QRect(40, 80, 121, 31))
        self.label_9.setObjectName("label_9")
        self.widget_7 = QtWidgets.QWidget(self.widget_4)
        self.widget_7.setGeometry(QtCore.QRect(20, 490, 221, 131))
        self.widget_7.setObjectName("widget_7")
        self.label_12 = QtWidgets.QLabel(self.widget_7)
        self.label_12.setGeometry(QtCore.QRect(0, 10, 191, 61))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        self.label_13.setGeometry(QtCore.QRect(40, 80, 121, 31))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.widget_4)
        self.label_15.setGeometry(QtCore.QRect(40, 30, 81, 41))
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(0, 30, 601, 401))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 480, 151, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 540, 151, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 500, 151, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 450, 151, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setGeometry(QtCore.QRect(340, 430, 251, 181))
        self.widget_5.setObjectName("widget_5")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_14 = QtWidgets.QLabel(self.widget_5)
        self.label_14.setGeometry(QtCore.QRect(30, 150, 72, 15))
        self.label_14.setObjectName("label_14")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 550, 151, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "人脸识别系统"))
        self.groupBox.setTitle(_translate("MainWindow", "功能"))
        self.pushButton.setText(_translate("MainWindow", "人脸检测"))
        self.pushButton_2.setText(_translate("MainWindow", "人脸识别"))
        self.pushButton_12.setText(_translate("MainWindow", "人脸分析"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据"))
        self.pushButton_3.setText(_translate("MainWindow", "数据列表"))
        self.pushButton_4.setText(_translate("MainWindow", "数据统计"))
        self.groupBox_3.setTitle(_translate("MainWindow", "设置"))
        self.pushButton_10.setText(_translate("MainWindow", "启动设置"))
        self.pushButton_11.setText(_translate("MainWindow", "数据设置"))
        self.label_4.setText(_translate("MainWindow", "Person_img_1"))
        self.label_5.setText(_translate("MainWindow", "Person_info_1"))
        self.label_10.setText(_translate("MainWindow", "Person_img_2"))
        self.label_11.setText(_translate("MainWindow", "Person_info_2"))
        self.label_8.setText(_translate("MainWindow", "Person_img_3"))
        self.label_9.setText(_translate("MainWindow", "Person_info_3"))
        self.label_12.setText(_translate("MainWindow", "Person_img_4"))
        self.label_13.setText(_translate("MainWindow", "Person_info_4"))
        self.label_15.setText(_translate("MainWindow", "信息展示"))
        self.label.setText(_translate("MainWindow", "Video "))
        self.pushButton_5.setText(_translate("MainWindow", "选择算法"))
        self.pushButton_6.setText(_translate("MainWindow", "选择分类器"))
        self.pushButton_7.setText(_translate("MainWindow", "打开视频"))
        self.pushButton_8.setText(_translate("MainWindow", "打开摄像头"))
        self.label_2.setText(_translate("MainWindow", "算法数据"))
        self.label_3.setText(_translate("MainWindow", "模型"))
        self.label_6.setText(_translate("MainWindow", "准确率"))
        self.label_14.setText(_translate("MainWindow", "分类器"))
        self.pushButton_9.setText(_translate("MainWindow", "抓取照片"))

